### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [vrandall66/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [ ] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [ ] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [ ] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [ ] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

Hey Vanessa!  Good job on your assessment. You are super close, but we want to make sure you understand the difference between what the programming concept of class is referring to and an actual class that is taken at school. Because both of your examples were examples of classes one would take in school, it's hard to tell whether you're misinterpreting the meaning of class as a programming concept. We want to see you model something other than a class that could be taught in a school. We want to give you some specific feedback for your `class_2.txt` file. Remember, this is a  `Class` not an `Object`. For your methods, make sure you are naming them as verbs/actions and try not to overthink them. `Snow Day` sounds like a boolean attribute and not a method, but the way you were thinking about it wasn't wrong based on your description. However, `modify_syllabus` would be a better choice of naming that clearly illustrates what you are doing and to which attribute. In fact, all of your descriptions would be better method names but in the present tense like `modify_grade`, or if you wanted to stick with what you had then you could name it something like `add_extra_credit` or `add_required_reading`. We want you to add to your assessment by thinking of a class that you would find in a furniture store. Create the class file named class_3.txt with a proper class name and add attributes and methods to the class the same way you did for the previous files. Add and commit these changes with a properly formatted commit message. Remember to commit these separate from your object file. Create a file named class_3_example_object.txt and make sure this example represents an instance of whatever you chose to model in the furniture store. Give the attributes you came up with in your class values and show us what the methods return the same way you had previously. Add and commit this file with a properly formatted commit message. Push your changes to Github. Send us a message when you've made these changes, so we can review and provide feedback. Reach out with any questions. Thanks Vanessa!

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready

**Comment by vrandall66** [comment]
Thank you for the feedback, Tim. I definitely misunderstood the first round through. I have added class_3.txt and class_3_example.txt to my repository with separate commits/messages for each document. This class and object example should be much better now.
